In [13]:
from sklearn.datasets import load_iris

# return_X_y=True : feature와 target만 받아오겠다는 말이다! 
dataxy=load_iris(return_X_y=True, as_frame=True)

In [14]:
feature=dataxy[0]
target=dataxy[1]

In [15]:
import pandas as np
import numpy as np
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(max_iter=1000)
model.fit(feature,target)
model.score(feature,target)

0.9733333333333334

In [16]:
model.predict(feature.head(1))

array([0])

In [17]:
model.predict(feature.iloc[[-1]])

array([2])

In [18]:
print(model.classes_)
print(model.feature_names_in_)
print(model.coef_)
print(model.n_iter_)
print(model.intercept_)

[0 1 2]
['sepal length (cm)' 'sepal width (cm)' 'petal length (cm)'
 'petal width (cm)']
[[-0.42323305  0.96708868 -2.51670007 -1.08081498]
 [ 0.53421916 -0.3215795  -0.20657535 -0.94373644]
 [-0.11098611 -0.64550918  2.72327542  2.02455142]]
[114]
[  9.84876748   2.2387132  -12.08748068]


In [19]:
# data=load_iris(as_frame=True)
# feature=data.data[:100]
# target=data.target[:100]

In [20]:
# model=LogisticRegression(max_iter=1000)
# model.fit(feature,target)
# model.score(feature,target)
# print(model.classes_)
# print(model.feature_names_in_)
# print(model.coef_) # 한 개만 알면 나머진 몰라도 되서 1개가 나온다! 
# print(model.n_iter_)
# print(model.intercept_)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

